require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/campi", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # Campi. As you add validations to Campi, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { "name" => 'Teste',
      "path" => 'Caminho'}
  }

  let(:invalid_attributes) {
    { "name" => 'Teste%',
      "path" => 'Caminho'}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Campi.create! valid_attributes
      get campi_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      campi = Campi.create! valid_attributes
      get campi_url(campi)
      expect(response).to be_successful
    end
  end
end
